### ISSUE TITLE
Buffer deprecation warning (Node 10)

### ISSUE THREAD

**Issue by martpie** [KnisterPeter/m3ujs#218]
I think this is coming from the `id3v2` package, but you probably know that better than me :)

```
internal/process/warning.js:18 (node:26157) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

**Comment by KnisterPeter** [comment]
@martpie  Thanks for reporting. The warning is printed out by node and you might be right by the idea it comes from `id3v2` but in fact its deeper in there and comes probably `iconv-lite`.
